[workspace]
members = [
    "contracts/swapp-note",
    "integration"
]
resolver = "2"
edition = "2021"

[workspace.dependencies]
miden = { git = "https://github.com/0xMiden/compiler", branch = "next" }


